---

- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
    - block:
      - name: Check if the deployed service is healthy
        uri: url=http://{{ HOST_IP }}
        register: COMMAND_RESULT  
        ignore_errors: true

      - name: Set FORCE=true if service is unhealthy
        set_fact: FORCE=true 
        when: COMMAND_RESULT | failed
        changed_when: COMMAND_RESULT | failed

      - name: (INCLUDE) Pull latest repo
        include: tasks/pull-latest-repo.yml

      - name: (INCLUDE) If repo has changed or the FORCE param equals true, then run a new deployment
        include: tasks/execute-deployment.yml
        when: "NEW_VERSION != OLD_VERSION or FORCE == true"

      rescue:
      - name: (INCLUDE) Reset cloned repo to a workable state
        include: tasks/reset-repo-to-workable-state.yml
